# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Block S3 Public Access for the AWS Account"

Resources:
  S3BlockPublicAccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.lambda_handler
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutAccountPublicAccessBlock
              Resource: "*"
      Runtime: python3.10
      Timeout: 300
  CheckResourceExist:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !GetAtt S3BlockPublicAccessFunction.Arn
      Region: !Ref AWS::Region
