# Copyright 2023 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Custom AWS Config rule

Globals:
  Function:
    Timeout: 5
    Tracing: Active
    Runtime: python3.10
    CodeUri: .

Resources:
  LambdaTracingRule:
    Type: AWS::Config::ConfigRule
    DependsOn: GeneralLambdaAccessPermission
    Properties:
      ConfigRuleName: ebs-volume-desired-type
      Description: Require Optimized EBS Volume Type
      InputParameters:
        {
          "resourceType": "AWS::EC2::Volume",
          "keyPath": "volumeType",
          "acceptedValues": ["gp3"],
        }
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Volume
      Source:
        Owner: CUSTOM_LAMBDA
        SourceIdentifier: !GetAtt GenericRuleLambda.Arn
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
          - EventSource: aws.config
            MessageType: OversizedConfigurationItemChangeNotification

  GenericRuleLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Description: Validator lambda for config params
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Action:
              - config:Put*
              - config:Get*
              - config:List*
              - config:Describe*
              - config:BatchGet*
              - config:Select*
            Effect: Allow
            Resource: "*"

  GeneralLambdaAccessPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GenericRuleLambda
      Principal: config.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"
